name: Build Artifacts
on: [push, pull_request]
jobs:
  build:
    name: Build Kotlin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.10"
      - name: Build with Gradle
        run: |
          cd kotlin
          gradle nativeCompile
          mv build/native/nativeCompile/mima-kotlin ../mima-kotlin
          cd ../c
          cmake -DCMAKE_BUILD_TYPE=Release
          make
          mv Mimamulator ../mima-c
          mv Assembler ../mimasm-c
          cd ..
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: kotlin
          path: |
            mima-kotlin
            mima-c
            mimasm-c